from HGConstants import *

OPTIONS = {
        'NODESIZE': NODESIZE, 'HITSIZE': HITSIZE, 'PASTE_OFFSET': PASTE_OFFSET, 'BLOB_CORNER_RADIUS': BLOB_CORNER_RADIUS,
        'DISPLAY_NAME_BY_DEFAULT': DISPLAY_NAME_BY_DEFAULT, 'DISPLAY_BLOB_DESCRIPTION_BY_DEFAULT': DISPLAY_BLOB_DESCRIPTION_BY_DEFAULT,
        'BLOB_FONT_SIZE': BLOB_FONT_SIZE, 'BLOB_FONT_IS_RESIZABLE': BLOB_FONT_IS_RESIZABLE, 'BLOB_NAME_ON_TOP': BLOB_NAME_ON_TOP,
        'DEFAULT_EDGE': DEFAULT_EDGE, 'ISDIGRAPH': ISDIGRAPH,
        'HOVER_COLOUR': HOVER_COLOUR, 'SELECT_COLOUR': SELECT_COLOUR,
        'DRAWING_COLOUR': DRAWING_COLOUR, 'BLOB_HANDLE_COLOUR': BLOB_HANDLE_COLOUR,
        'EDGE_HANDLE_COLOUR': EDGE_HANDLE_COLOUR
}